# Generated by Django 5.2.3 on 2025-06-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='url',
            field=models.TextField(blank=True, help_text='URL del proyecto si está disponible', null=True),
        ),
    ]
