FROM node:20-alpine AS builder

WORKDIR /app
COPY ./app .
RUN npm install
RUN npm run build --prod

FROM nginx:stable-alpine
COPY --from=builder /app/dist/portfolio/browser /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 4200